
.. _core-developers-team:


.. raw:: html

    <div class="team-grid">

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/6051075?v=4"
        alt="Avatar picture of @plaresmedima"
        class="team-avatar"
        />
        <a href="https://github.com/plaresmedima" class="team-name">Steven Sourbron</a>
        <div class="team-handle">@plaresmedima</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/100941618?v=4"
        alt="Avatar picture of @EbonyGunwhy"
        class="team-avatar"
        />
        <a href="https://github.com/EbonyGunwhy" class="team-name">Ebony Gunwhy</a>
        <div class="team-handle">@EbonyGunwhy</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/108075275?v=4"
        alt="Avatar picture of @EveLMedPhys"
        class="team-avatar"
        />
        <a href="https://github.com/EveLMedPhys" class="team-name">Eve Lennie</a>
        <div class="team-handle">@EveLMedPhys</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/53518061?v=4"
        alt="Avatar picture of @JSousa-UoL"
        class="team-avatar"
        />
        <a href="https://github.com/JSousa-UoL" class="team-name">João Almeida e Sousa</a>
        <div class="team-handle">@JSousa-UoL</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/48806417?v=4"
        alt="Avatar picture of @JoaoPeriquito"
        class="team-avatar"
        />
        <a href="https://github.com/JoaoPeriquito" class="team-name">Joao Periquito</a>
        <div class="team-handle">@JoaoPeriquito</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/42036722?v=4"
        alt="Avatar picture of @KanishkaS"
        class="team-avatar"
        />
        <a href="https://github.com/KanishkaS" class="team-name">Kanishka Sharma</a>
        <div class="team-handle">@KanishkaS</div>
    </div>

    <!-- Add more team members here -->
    </div>
